import { pickRandom, type WeightedOption, weightedRandom } from '../utils.js';

interface GeoLocation {
  country: string;
  region: string;
  city: string;
}

interface Location {
  region?: string;
  city: string;
}

interface CountryProfile {
  /** Relative traffic weight (unnormalized). */
  weight: number;
  /** Cities visitors come from; region is an ISO 3166-2 code (without the country prefix). */
  locations: Location[];
  /** BCP 47 language tags visitors from this country typically use. */
  languages?: string[];
}

function loc(city: string, region?: string): Location {
  return { city, region };
}

/**
 * Traffic profile for every ISO 3166-1 country and territory known to the app
 * (see public/intl/country/en-US.json). Weights roughly follow internet
 * population with a bias towards English-speaking markets. Large markets list
 * several cities with ISO 3166-2 regions; the long tail uses the capital or
 * largest city so that every country still appears in the seeded data.
 */
const countries: Record<string, CountryProfile> = {
  // ── Tier 1: major markets ────────────────────────────────────────────────
  US: {
    weight: 2200,
    languages: ['en-US', 'en-US', 'en-US', 'es-US'],
    locations: [
      loc('San Francisco', 'CA'),
      loc('Los Angeles', 'CA'),
      loc('San Diego', 'CA'),
      loc('New York', 'NY'),
      loc('Brooklyn', 'NY'),
      loc('Austin', 'TX'),
      loc('Houston', 'TX'),
      loc('Dallas', 'TX'),
      loc('Seattle', 'WA'),
      loc('Chicago', 'IL'),
      loc('Boston', 'MA'),
      loc('Denver', 'CO'),
      loc('Atlanta', 'GA'),
      loc('Miami', 'FL'),
      loc('Orlando', 'FL'),
      loc('Philadelphia', 'PA'),
      loc('Pittsburgh', 'PA'),
      loc('Phoenix', 'AZ'),
      loc('Minneapolis', 'MN'),
      loc('Portland', 'OR'),
      loc('Charlotte', 'NC'),
      loc('Raleigh', 'NC'),
      loc('Nashville', 'TN'),
      loc('Detroit', 'MI'),
      loc('Salt Lake City', 'UT'),
      loc('Las Vegas', 'NV'),
      loc('Washington', 'DC'),
      loc('Columbus', 'OH'),
      loc('Indianapolis', 'IN'),
      loc('St. Louis', 'MO'),
    ],
  },
  IN: {
    weight: 800,
    languages: ['en-IN', 'hi-IN', 'en-IN', 'ta-IN', 'te-IN', 'bn-IN', 'mr-IN'],
    locations: [
      loc('Mumbai', 'MH'),
      loc('Pune', 'MH'),
      loc('Bengaluru', 'KA'),
      loc('New Delhi', 'DL'),
      loc('Chennai', 'TN'),
      loc('Hyderabad', 'TG'),
      loc('Kolkata', 'WB'),
      loc('Ahmedabad', 'GJ'),
      loc('Jaipur', 'RJ'),
      loc('Lucknow', 'UP'),
      loc('Chandigarh', 'CH'),
      loc('Kochi', 'KL'),
    ],
  },
  GB: {
    weight: 520,
    languages: ['en-GB'],
    locations: [
      loc('London', 'ENG'),
      loc('Manchester', 'ENG'),
      loc('Birmingham', 'ENG'),
      loc('Leeds', 'ENG'),
      loc('Bristol', 'ENG'),
      loc('Liverpool', 'ENG'),
      loc('Newcastle upon Tyne', 'ENG'),
      loc('Edinburgh', 'SCT'),
      loc('Glasgow', 'SCT'),
      loc('Cardiff', 'WLS'),
      loc('Belfast', 'NIR'),
    ],
  },
  DE: {
    weight: 420,
    languages: ['de-DE', 'de-DE', 'en-GB'],
    locations: [
      loc('Berlin', 'BE'),
      loc('Munich', 'BY'),
      loc('Nuremberg', 'BY'),
      loc('Hamburg', 'HH'),
      loc('Frankfurt', 'HE'),
      loc('Cologne', 'NW'),
      loc('Düsseldorf', 'NW'),
      loc('Stuttgart', 'BW'),
      loc('Leipzig', 'SN'),
      loc('Dresden', 'SN'),
      loc('Hanover', 'NI'),
      loc('Bremen', 'HB'),
    ],
  },
  CN: {
    weight: 400,
    languages: ['zh-CN'],
    locations: [
      loc('Beijing', 'BJ'),
      loc('Shanghai', 'SH'),
      loc('Shenzhen', 'GD'),
      loc('Guangzhou', 'GD'),
      loc('Chengdu', 'SC'),
      loc('Hangzhou', 'ZJ'),
      loc('Nanjing', 'JS'),
      loc('Wuhan', 'HB'),
      loc('Xi’an', 'SN'),
      loc('Chongqing', 'CQ'),
      loc('Tianjin', 'TJ'),
    ],
  },
  BR: {
    weight: 360,
    languages: ['pt-BR'],
    locations: [
      loc('São Paulo', 'SP'),
      loc('Campinas', 'SP'),
      loc('Rio de Janeiro', 'RJ'),
      loc('Belo Horizonte', 'MG'),
      loc('Brasília', 'DF'),
      loc('Curitiba', 'PR'),
      loc('Porto Alegre', 'RS'),
      loc('Salvador', 'BA'),
      loc('Recife', 'PE'),
      loc('Fortaleza', 'CE'),
      loc('Florianópolis', 'SC'),
    ],
  },
  FR: {
    weight: 320,
    languages: ['fr-FR', 'fr-FR', 'en-GB'],
    locations: [
      loc('Paris', 'IDF'),
      loc('Lyon', 'ARA'),
      loc('Grenoble', 'ARA'),
      loc('Marseille', 'PAC'),
      loc('Nice', 'PAC'),
      loc('Toulouse', 'OCC'),
      loc('Montpellier', 'OCC'),
      loc('Bordeaux', 'NAQ'),
      loc('Lille', 'HDF'),
      loc('Nantes', 'PDL'),
      loc('Strasbourg', 'GES'),
      loc('Rennes', 'BRE'),
    ],
  },
  CA: {
    weight: 320,
    languages: ['en-CA', 'en-CA', 'fr-CA'],
    locations: [
      loc('Toronto', 'ON'),
      loc('Ottawa', 'ON'),
      loc('Waterloo', 'ON'),
      loc('Vancouver', 'BC'),
      loc('Victoria', 'BC'),
      loc('Montreal', 'QC'),
      loc('Quebec City', 'QC'),
      loc('Calgary', 'AB'),
      loc('Edmonton', 'AB'),
      loc('Winnipeg', 'MB'),
      loc('Halifax', 'NS'),
      loc('Saskatoon', 'SK'),
    ],
  },
  JP: {
    weight: 300,
    languages: ['ja-JP'],
    locations: [
      loc('Tokyo', '13'),
      loc('Yokohama', '14'),
      loc('Osaka', '27'),
      loc('Nagoya', '23'),
      loc('Fukuoka', '40'),
      loc('Sapporo', '01'),
      loc('Kyoto', '26'),
      loc('Kobe', '28'),
      loc('Sendai', '04'),
      loc('Hiroshima', '34'),
    ],
  },
  ID: {
    weight: 260,
    languages: ['id-ID', 'id-ID', 'en-US'],
    locations: [
      loc('Jakarta', 'JK'),
      loc('Bandung', 'JB'),
      loc('Surabaya', 'JI'),
      loc('Yogyakarta', 'YO'),
      loc('Denpasar', 'BA'),
      loc('Medan', 'SU'),
      loc('Makassar', 'SN'),
      loc('Semarang', 'JT'),
    ],
  },
  MX: {
    weight: 250,
    languages: ['es-MX'],
    locations: [
      loc('Mexico City', 'CMX'),
      loc('Guadalajara', 'JAL'),
      loc('Monterrey', 'NLE'),
      loc('Puebla', 'PUE'),
      loc('Tijuana', 'BCN'),
      loc('Querétaro', 'QUE'),
      loc('Mérida', 'YUC'),
      loc('Cancún', 'ROO'),
      loc('León', 'GUA'),
    ],
  },
  AU: {
    weight: 230,
    languages: ['en-AU'],
    locations: [
      loc('Sydney', 'NSW'),
      loc('Newcastle', 'NSW'),
      loc('Melbourne', 'VIC'),
      loc('Geelong', 'VIC'),
      loc('Brisbane', 'QLD'),
      loc('Gold Coast', 'QLD'),
      loc('Perth', 'WA'),
      loc('Adelaide', 'SA'),
      loc('Canberra', 'ACT'),
      loc('Hobart', 'TAS'),
      loc('Darwin', 'NT'),
    ],
  },
  RU: {
    weight: 200,
    languages: ['ru-RU'],
    locations: [
      loc('Moscow', 'MOW'),
      loc('Saint Petersburg', 'SPE'),
      loc('Novosibirsk', 'NVS'),
      loc('Yekaterinburg', 'SVE'),
      loc('Kazan', 'TA'),
      loc('Nizhny Novgorod', 'NIZ'),
      loc('Krasnodar', 'KDA'),
      loc('Samara', 'SAM'),
    ],
  },
  KR: {
    weight: 200,
    languages: ['ko-KR'],
    locations: [
      loc('Seoul', '11'),
      loc('Busan', '26'),
      loc('Daegu', '27'),
      loc('Incheon', '28'),
      loc('Gwangju', '29'),
      loc('Daejeon', '30'),
      loc('Suwon', '41'),
    ],
  },
  ES: {
    weight: 200,
    languages: ['es-ES', 'es-ES', 'ca-ES'],
    locations: [
      loc('Madrid', 'MD'),
      loc('Barcelona', 'CT'),
      loc('Valencia', 'VC'),
      loc('Seville', 'AN'),
      loc('Málaga', 'AN'),
      loc('Bilbao', 'PV'),
      loc('Zaragoza', 'AR'),
      loc('Palma', 'IB'),
      loc('Las Palmas', 'CN'),
    ],
  },
  IT: {
    weight: 200,
    languages: ['it-IT'],
    locations: [
      loc('Rome', '62'),
      loc('Milan', '25'),
      loc('Naples', '72'),
      loc('Turin', '21'),
      loc('Florence', '52'),
      loc('Bologna', '45'),
      loc('Venice', '34'),
      loc('Genoa', '42'),
      loc('Palermo', '82'),
      loc('Bari', '75'),
    ],
  },
  NL: {
    weight: 160,
    languages: ['nl-NL', 'nl-NL', 'en-GB'],
    locations: [
      loc('Amsterdam', 'NH'),
      loc('Haarlem', 'NH'),
      loc('Rotterdam', 'ZH'),
      loc('The Hague', 'ZH'),
      loc('Utrecht', 'UT'),
      loc('Eindhoven', 'NB'),
      loc('Groningen', 'GR'),
      loc('Arnhem', 'GE'),
    ],
  },
  PL: {
    weight: 150,
    languages: ['pl-PL'],
    locations: [
      loc('Warsaw', '14'),
      loc('Kraków', '12'),
      loc('Wrocław', '02'),
      loc('Poznań', '30'),
      loc('Gdańsk', '22'),
      loc('Łódź', '10'),
      loc('Katowice', '24'),
    ],
  },
  TR: {
    weight: 150,
    languages: ['tr-TR'],
    locations: [
      loc('Istanbul', '34'),
      loc('Ankara', '06'),
      loc('Izmir', '35'),
      loc('Bursa', '16'),
      loc('Antalya', '07'),
      loc('Adana', '01'),
    ],
  },
  PH: {
    weight: 150,
    languages: ['en-PH', 'fil-PH'],
    locations: [
      loc('Manila', '00'),
      loc('Quezon City', '00'),
      loc('Makati', '00'),
      loc('Cebu City', 'CEB'),
      loc('Davao City', 'DAS'),
      loc('Iloilo City', 'ILI'),
    ],
  },
  VN: {
    weight: 130,
    languages: ['vi-VN'],
    locations: [
      loc('Hanoi', 'HN'),
      loc('Ho Chi Minh City', 'SG'),
      loc('Da Nang', 'DN'),
      loc('Hai Phong', 'HP'),
      loc('Can Tho', 'CT'),
    ],
  },
  TH: {
    weight: 120,
    languages: ['th-TH'],
    locations: [
      loc('Bangkok', '10'),
      loc('Nonthaburi', '12'),
      loc('Chiang Mai', '50'),
      loc('Pattaya', '20'),
      loc('Phuket', '83'),
      loc('Khon Kaen', '40'),
    ],
  },
  NG: {
    weight: 120,
    languages: ['en-NG'],
    locations: [
      loc('Lagos', 'LA'),
      loc('Abuja', 'FC'),
      loc('Kano', 'KN'),
      loc('Ibadan', 'OY'),
      loc('Port Harcourt', 'RI'),
      loc('Enugu', 'EN'),
    ],
  },
  PK: {
    weight: 120,
    languages: ['en-PK', 'ur-PK'],
    locations: [
      loc('Lahore', 'PB'),
      loc('Rawalpindi', 'PB'),
      loc('Karachi', 'SD'),
      loc('Islamabad', 'IS'),
      loc('Peshawar', 'KP'),
    ],
  },
  BD: {
    weight: 100,
    languages: ['bn-BD'],
    locations: [loc('Dhaka', 'C'), loc('Chittagong', 'B'), loc('Sylhet', 'G'), loc('Khulna', 'D')],
  },
  EG: {
    weight: 100,
    languages: ['ar-EG'],
    locations: [
      loc('Cairo', 'C'),
      loc('Alexandria', 'ALX'),
      loc('Giza', 'GZ'),
      loc('Mansoura', 'DK'),
    ],
  },
  AR: {
    weight: 100,
    languages: ['es-AR'],
    locations: [
      loc('Buenos Aires', 'C'),
      loc('La Plata', 'B'),
      loc('Córdoba', 'X'),
      loc('Rosario', 'S'),
      loc('Mendoza', 'M'),
    ],
  },
  CO: {
    weight: 90,
    languages: ['es-CO'],
    locations: [
      loc('Bogotá', 'DC'),
      loc('Medellín', 'ANT'),
      loc('Cali', 'VAC'),
      loc('Barranquilla', 'ATL'),
      loc('Cartagena', 'BOL'),
    ],
  },
  ZA: {
    weight: 90,
    languages: ['en-ZA', 'en-ZA', 'af-ZA'],
    locations: [
      loc('Johannesburg', 'GP'),
      loc('Pretoria', 'GP'),
      loc('Cape Town', 'WC'),
      loc('Durban', 'KZN'),
      loc('Gqeberha', 'EC'),
    ],
  },
  UA: {
    weight: 80,
    languages: ['uk-UA', 'uk-UA', 'ru-UA'],
    locations: [
      loc('Kyiv', '30'),
      loc('Kharkiv', '63'),
      loc('Lviv', '46'),
      loc('Odesa', '51'),
      loc('Dnipro', '12'),
    ],
  },
  SE: {
    weight: 80,
    languages: ['sv-SE', 'sv-SE', 'en-GB'],
    locations: [
      loc('Stockholm', 'AB'),
      loc('Gothenburg', 'O'),
      loc('Malmö', 'M'),
      loc('Uppsala', 'C'),
    ],
  },
  SA: {
    weight: 80,
    languages: ['ar-SA', 'ar-SA', 'en-US'],
    locations: [loc('Riyadh', '01'), loc('Jeddah', '02'), loc('Dammam', '04'), loc('Medina', '03')],
  },
  MY: {
    weight: 80,
    languages: ['en-MY', 'ms-MY', 'zh-CN'],
    locations: [
      loc('Kuala Lumpur', '14'),
      loc('Petaling Jaya', '10'),
      loc('George Town', '07'),
      loc('Johor Bahru', '01'),
      loc('Kota Kinabalu', '12'),
    ],
  },
  TW: {
    weight: 70,
    languages: ['zh-TW'],
    locations: [
      loc('Taipei', 'TPE'),
      loc('New Taipei', 'NWT'),
      loc('Kaohsiung', 'KHH'),
      loc('Taichung', 'TXG'),
      loc('Tainan', 'TNN'),
    ],
  },
  SG: { weight: 70, languages: ['en-SG', 'en-SG', 'zh-CN'], locations: [loc('Singapore')] },
  AE: {
    weight: 70,
    languages: ['en-US', 'ar-AE'],
    locations: [loc('Dubai', 'DU'), loc('Abu Dhabi', 'AZ'), loc('Sharjah', 'SH')],
  },
  CH: {
    weight: 70,
    languages: ['de-CH', 'fr-CH', 'it-CH', 'en-GB'],
    locations: [
      loc('Zurich', 'ZH'),
      loc('Geneva', 'GE'),
      loc('Basel', 'BS'),
      loc('Bern', 'BE'),
      loc('Lausanne', 'VD'),
    ],
  },
  BE: {
    weight: 70,
    languages: ['nl-BE', 'fr-BE', 'en-GB'],
    locations: [
      loc('Brussels', 'BRU'),
      loc('Antwerp', 'VAN'),
      loc('Ghent', 'VOV'),
      loc('Liège', 'WLG'),
      loc('Leuven', 'VBR'),
    ],
  },
  HK: { weight: 60, languages: ['zh-HK', 'en-HK'], locations: [loc('Hong Kong')] },
  IL: {
    weight: 60,
    languages: ['he-IL', 'he-IL', 'en-US'],
    locations: [
      loc('Tel Aviv', 'TA'),
      loc('Jerusalem', 'JM'),
      loc('Haifa', 'HA'),
      loc('Beersheba', 'D'),
    ],
  },
  IR: {
    weight: 60,
    languages: ['fa-IR'],
    locations: [
      loc('Tehran', '23'),
      loc('Isfahan', '10'),
      loc('Mashhad', '09'),
      loc('Shiraz', '07'),
    ],
  },
  AT: {
    weight: 50,
    languages: ['de-AT'],
    locations: [
      loc('Vienna', '9'),
      loc('Salzburg', '5'),
      loc('Linz', '4'),
      loc('Graz', '6'),
      loc('Innsbruck', '7'),
    ],
  },
  PT: {
    weight: 50,
    languages: ['pt-PT'],
    locations: [loc('Lisbon', '11'), loc('Porto', '13'), loc('Braga', '03'), loc('Coimbra', '06')],
  },
  IE: {
    weight: 50,
    languages: ['en-IE'],
    locations: [loc('Dublin', 'D'), loc('Cork', 'CO'), loc('Galway', 'G'), loc('Limerick', 'LK')],
  },
  NO: {
    weight: 50,
    languages: ['nb-NO', 'nb-NO', 'en-GB'],
    locations: [
      loc('Oslo', '03'),
      loc('Bergen', '46'),
      loc('Trondheim', '50'),
      loc('Stavanger', '11'),
    ],
  },
  DK: {
    weight: 50,
    languages: ['da-DK', 'da-DK', 'en-GB'],
    locations: [
      loc('Copenhagen', '84'),
      loc('Aarhus', '82'),
      loc('Odense', '83'),
      loc('Aalborg', '81'),
    ],
  },
  FI: {
    weight: 50,
    languages: ['fi-FI', 'fi-FI', 'en-GB'],
    locations: [
      loc('Helsinki', '18'),
      loc('Espoo', '18'),
      loc('Tampere', '11'),
      loc('Oulu', '14'),
      loc('Turku', '19'),
    ],
  },
  CZ: {
    weight: 50,
    languages: ['cs-CZ'],
    locations: [loc('Prague', '10'), loc('Brno', '64'), loc('Ostrava', '80'), loc('Plzeň', '32')],
  },
  RO: {
    weight: 50,
    languages: ['ro-RO'],
    locations: [
      loc('Bucharest', 'B'),
      loc('Cluj-Napoca', 'CJ'),
      loc('Timișoara', 'TM'),
      loc('Iași', 'IS'),
    ],
  },
  NZ: {
    weight: 50,
    languages: ['en-NZ'],
    locations: [
      loc('Auckland', 'AUK'),
      loc('Wellington', 'WGN'),
      loc('Christchurch', 'CAN'),
      loc('Hamilton', 'WKO'),
    ],
  },
  CL: {
    weight: 50,
    languages: ['es-CL'],
    locations: [
      loc('Santiago', 'RM'),
      loc('Valparaíso', 'VS'),
      loc('Concepción', 'BI'),
      loc('Antofagasta', 'AN'),
    ],
  },
  PE: {
    weight: 50,
    languages: ['es-PE'],
    locations: [
      loc('Lima', 'LIM'),
      loc('Arequipa', 'ARE'),
      loc('Trujillo', 'LAL'),
      loc('Cusco', 'CUS'),
    ],
  },
  KE: {
    weight: 50,
    languages: ['en-KE', 'sw-KE'],
    locations: [
      loc('Nairobi', '30'),
      loc('Mombasa', '28'),
      loc('Kisumu', '42'),
      loc('Nakuru', '31'),
    ],
  },
  GR: {
    weight: 40,
    languages: ['el-GR'],
    locations: [
      loc('Athens', 'I'),
      loc('Thessaloniki', 'B'),
      loc('Patras', 'G'),
      loc('Heraklion', 'M'),
    ],
  },
  HU: {
    weight: 40,
    languages: ['hu-HU'],
    locations: [
      loc('Budapest', 'BU'),
      loc('Debrecen', 'HB'),
      loc('Szeged', 'CS'),
      loc('Pécs', 'BA'),
    ],
  },
  MA: {
    weight: 40,
    languages: ['fr-MA', 'ar-MA'],
    locations: [
      loc('Casablanca', '06'),
      loc('Rabat', '04'),
      loc('Marrakesh', '07'),
      loc('Tangier', '01'),
    ],
  },
  DZ: {
    weight: 35,
    languages: ['ar-DZ', 'fr-DZ'],
    locations: [loc('Algiers', '16'), loc('Oran', '31'), loc('Constantine', '25')],
  },
  IQ: {
    weight: 35,
    languages: ['ar-IQ'],
    locations: [loc('Baghdad', 'BG'), loc('Basra', 'BA'), loc('Erbil', 'AR'), loc('Mosul', 'NI')],
  },
  GH: {
    weight: 30,
    languages: ['en-GH'],
    locations: [loc('Accra', 'AA'), loc('Kumasi', 'AH'), loc('Tamale', 'NP')],
  },
  ET: {
    weight: 30,
    languages: ['am-ET', 'en-US'],
    locations: [loc('Addis Ababa', 'AA'), loc('Dire Dawa', 'DD'), loc('Bahir Dar', 'AM')],
  },
  TZ: {
    weight: 25,
    languages: ['sw-TZ', 'en-US'],
    locations: [
      loc('Dar es Salaam', '02'),
      loc('Dodoma', '03'),
      loc('Arusha', '01'),
      loc('Mwanza', '18'),
    ],
  },
  UG: {
    weight: 20,
    languages: ['en-UG'],
    locations: [loc('Kampala', '102'), loc('Entebbe', '102'), loc('Gulu', '304')],
  },
  EC: {
    weight: 25,
    languages: ['es-EC'],
    locations: [loc('Quito', 'P'), loc('Guayaquil', 'G'), loc('Cuenca', 'A')],
  },
  VE: {
    weight: 25,
    languages: ['es-VE'],
    locations: [loc('Caracas', 'A'), loc('Maracaibo', 'V'), loc('Valencia', 'G')],
  },
  UZ: {
    weight: 25,
    languages: ['uz-UZ', 'ru-RU'],
    locations: [loc('Tashkent', 'TK'), loc('Samarkand', 'SA')],
  },
  KZ: {
    weight: 25,
    languages: ['ru-KZ', 'kk-KZ'],
    locations: [loc('Almaty', '75'), loc('Astana', '71'), loc('Shymkent', '79')],
  },
  LK: {
    weight: 25,
    languages: ['si-LK', 'en-US'],
    locations: [loc('Colombo', '1'), loc('Kandy', '2')],
  },
  NP: {
    weight: 25,
    languages: ['ne-NP', 'en-US'],
    locations: [loc('Kathmandu', 'BA'), loc('Pokhara', 'GA')],
  },
  MM: {
    weight: 20,
    languages: ['my-MM'],
    locations: [loc('Yangon', '06'), loc('Mandalay', '04'), loc('Naypyidaw', '18')],
  },
  KH: {
    weight: 15,
    languages: ['km-KH'],
    locations: [loc('Phnom Penh', '12'), loc('Siem Reap', '17')],
  },
  BG: {
    weight: 30,
    languages: ['bg-BG'],
    locations: [loc('Sofia', '22'), loc('Plovdiv', '16'), loc('Varna', '03')],
  },
  RS: {
    weight: 30,
    languages: ['sr-RS'],
    locations: [loc('Belgrade', '00'), loc('Novi Sad'), loc('Niš', '20')],
  },
  HR: {
    weight: 25,
    languages: ['hr-HR'],
    locations: [loc('Zagreb', '21'), loc('Split', '17'), loc('Rijeka', '08')],
  },
  SK: {
    weight: 25,
    languages: ['sk-SK'],
    locations: [loc('Bratislava', 'BL'), loc('Košice', 'KI')],
  },
  SI: {
    weight: 20,
    languages: ['sl-SI'],
    locations: [loc('Ljubljana', '061'), loc('Maribor', '070')],
  },
  LT: {
    weight: 20,
    languages: ['lt-LT'],
    locations: [loc('Vilnius', 'VL'), loc('Kaunas', 'KU'), loc('Klaipėda', 'KL')],
  },
  LV: {
    weight: 20,
    languages: ['lv-LV'],
    locations: [loc('Riga', 'RIX'), loc('Daugavpils', 'DGV')],
  },
  EE: {
    weight: 20,
    languages: ['et-EE', 'en-GB'],
    locations: [loc('Tallinn', '37'), loc('Tartu', '79')],
  },
  BY: {
    weight: 20,
    languages: ['ru-BY', 'be-BY'],
    locations: [loc('Minsk', 'HM'), loc('Gomel', 'HO')],
  },
  MD: {
    weight: 10,
    languages: ['ro-MD', 'ru-RU'],
    locations: [loc('Chișinău', 'CU'), loc('Bălți', 'BA')],
  },
  GE: { weight: 15, languages: ['ka-GE'], locations: [loc('Tbilisi', 'TB'), loc('Batumi', 'AJ')] },
  AM: { weight: 12, languages: ['hy-AM'], locations: [loc('Yerevan', 'ER'), loc('Gyumri', 'SH')] },
  AZ: { weight: 15, languages: ['az-AZ'], locations: [loc('Baku', 'BA'), loc('Ganja', 'GA')] },
  LU: {
    weight: 12,
    languages: ['fr-LU', 'de-LU', 'en-GB'],
    locations: [loc('Luxembourg', 'LU'), loc('Esch-sur-Alzette', 'ES')],
  },
  IS: {
    weight: 10,
    languages: ['is-IS', 'en-GB'],
    locations: [loc('Reykjavík', '1'), loc('Akureyri', '6')],
  },
  MT: {
    weight: 8,
    languages: ['en-MT', 'mt-MT'],
    locations: [loc('Valletta', '60'), loc('Sliema', '56')],
  },
  CY: {
    weight: 10,
    languages: ['el-CY', 'en-GB'],
    locations: [loc('Nicosia', '01'), loc('Limassol', '02')],
  },
  AL: { weight: 10, languages: ['sq-AL'], locations: [loc('Tirana', '11'), loc('Durrës', '02')] },
  MK: { weight: 8, languages: ['mk-MK'], locations: [loc('Skopje', '814'), loc('Bitola', '501')] },
  BA: {
    weight: 10,
    languages: ['bs-BA'],
    locations: [loc('Sarajevo', 'BIH'), loc('Banja Luka', 'SRP')],
  },
  ME: { weight: 5, languages: ['sr-ME'], locations: [loc('Podgorica', '16'), loc('Budva', '05')] },
  XK: { weight: 5, languages: ['sq-XK'], locations: [loc('Pristina')] },
  JO: {
    weight: 15,
    languages: ['ar-JO', 'en-US'],
    locations: [loc('Amman', 'AM'), loc('Irbid', 'IR'), loc('Zarqa', 'AZ')],
  },
  LB: {
    weight: 12,
    languages: ['ar-LB', 'fr-LB', 'en-US'],
    locations: [loc('Beirut', 'BA'), loc('Tripoli', 'AS')],
  },
  KW: {
    weight: 12,
    languages: ['ar-KW', 'en-US'],
    locations: [loc('Kuwait City', 'KU'), loc('Hawalli', 'HA')],
  },
  QA: {
    weight: 12,
    languages: ['ar-QA', 'en-US'],
    locations: [loc('Doha', 'DA'), loc('Al Rayyan', 'RA')],
  },
  BH: {
    weight: 8,
    languages: ['ar-BH', 'en-US'],
    locations: [loc('Manama', '13'), loc('Riffa', '15')],
  },
  OM: {
    weight: 10,
    languages: ['ar-OM', 'en-US'],
    locations: [loc('Muscat', 'MA'), loc('Salalah', 'ZU')],
  },
  YE: { weight: 8, languages: ['ar-YE'], locations: [loc('Sanaa', 'SA'), loc('Aden', 'AD')] },
  SY: { weight: 8, languages: ['ar-SY'], locations: [loc('Damascus', 'DI'), loc('Aleppo', 'HL')] },
  PS: { weight: 8, languages: ['ar-PS'], locations: [loc('Ramallah', 'RBH'), loc('Gaza', 'GZA')] },
  TN: {
    weight: 15,
    languages: ['ar-TN', 'fr-TN'],
    locations: [loc('Tunis', '11'), loc('Sfax', '61'), loc('Sousse', '51')],
  },
  LY: { weight: 8, languages: ['ar-LY'], locations: [loc('Tripoli', 'TB'), loc('Benghazi', 'BA')] },
  SD: {
    weight: 10,
    languages: ['ar-SD'],
    locations: [loc('Khartoum', 'KH'), loc('Omdurman', 'KH')],
  },
  SS: { weight: 3, languages: ['en-US'], locations: [loc('Juba', 'EC')] },
  ER: { weight: 2, languages: ['ti-ER'], locations: [loc('Asmara', 'MA')] },
  DJ: { weight: 2, languages: ['fr-DJ'], locations: [loc('Djibouti', 'DJ')] },
  SO: {
    weight: 5,
    languages: ['so-SO'],
    locations: [loc('Mogadishu', 'BN'), loc('Hargeisa', 'WO')],
  },
  RW: { weight: 8, languages: ['en-US', 'rw-RW', 'fr-FR'], locations: [loc('Kigali', '01')] },
  BI: { weight: 3, languages: ['fr-BI'], locations: [loc('Bujumbura', 'BM'), loc('Gitega', 'GI')] },
  CD: {
    weight: 12,
    languages: ['fr-CD'],
    locations: [loc('Kinshasa', 'KN'), loc('Lubumbashi', 'HK'), loc('Goma', 'NK')],
  },
  CG: {
    weight: 4,
    languages: ['fr-CG'],
    locations: [loc('Brazzaville', 'BZV'), loc('Pointe-Noire', '16')],
  },
  CM: {
    weight: 12,
    languages: ['fr-CM', 'en-CM'],
    locations: [loc('Douala', 'LT'), loc('Yaoundé', 'CE')],
  },
  CI: {
    weight: 12,
    languages: ['fr-CI'],
    locations: [loc('Abidjan', 'AB'), loc('Yamoussoukro', 'YM')],
  },
  SN: { weight: 10, languages: ['fr-SN'], locations: [loc('Dakar', 'DK'), loc('Thiès', 'TH')] },
  ML: { weight: 5, languages: ['fr-ML'], locations: [loc('Bamako', 'BKO')] },
  BF: {
    weight: 5,
    languages: ['fr-BF'],
    locations: [loc('Ouagadougou', 'KAD'), loc('Bobo-Dioulasso', 'HOU')],
  },
  NE: { weight: 4, languages: ['fr-NE'], locations: [loc('Niamey', '8')] },
  TD: { weight: 3, languages: ['fr-TD'], locations: [loc('N’Djamena', 'ND')] },
  CF: { weight: 2, languages: ['fr-CF'], locations: [loc('Bangui', 'BGF')] },
  GA: { weight: 4, languages: ['fr-GA'], locations: [loc('Libreville', '1')] },
  GQ: { weight: 2, languages: ['es-GQ'], locations: [loc('Malabo', 'BN')] },
  TG: { weight: 5, languages: ['fr-TG'], locations: [loc('Lomé', 'M')] },
  BJ: {
    weight: 5,
    languages: ['fr-BJ'],
    locations: [loc('Cotonou', 'LI'), loc('Porto-Novo', 'OU')],
  },
  GN: { weight: 4, languages: ['fr-GN'], locations: [loc('Conakry', 'C')] },
  GW: { weight: 2, languages: ['pt-GW'], locations: [loc('Bissau', 'BS')] },
  GM: { weight: 3, languages: ['en-GM'], locations: [loc('Banjul', 'B')] },
  SL: { weight: 4, languages: ['en-SL'], locations: [loc('Freetown', 'W')] },
  LR: { weight: 3, languages: ['en-LR'], locations: [loc('Monrovia', 'MO')] },
  MR: { weight: 3, languages: ['ar-MR', 'fr-MR'], locations: [loc('Nouakchott', '13')] },
  CV: { weight: 2, languages: ['pt-CV'], locations: [loc('Praia', 'PR')] },
  ST: { weight: 1, languages: ['pt-ST'], locations: [loc('São Tomé', '01')] },
  AO: {
    weight: 8,
    languages: ['pt-AO'],
    locations: [loc('Luanda', 'LUA'), loc('Benguela', 'BGU')],
  },
  MZ: { weight: 8, languages: ['pt-MZ'], locations: [loc('Maputo', 'L'), loc('Beira', 'S')] },
  ZM: { weight: 8, languages: ['en-ZM'], locations: [loc('Lusaka', '09'), loc('Kitwe', '08')] },
  ZW: { weight: 8, languages: ['en-ZW'], locations: [loc('Harare', 'HA'), loc('Bulawayo', 'BU')] },
  MW: {
    weight: 5,
    languages: ['en-MW'],
    locations: [loc('Lilongwe', 'LI'), loc('Blantyre', 'BL')],
  },
  BW: {
    weight: 5,
    languages: ['en-BW'],
    locations: [loc('Gaborone', 'SE'), loc('Francistown', 'NE')],
  },
  NA: {
    weight: 5,
    languages: ['en-NA'],
    locations: [loc('Windhoek', 'KH'), loc('Swakopmund', 'ER')],
  },
  LS: { weight: 2, languages: ['en-LS'], locations: [loc('Maseru', 'A')] },
  SZ: { weight: 2, languages: ['en-SZ'], locations: [loc('Mbabane', 'HH'), loc('Manzini', 'MA')] },
  MG: { weight: 5, languages: ['fr-MG', 'mg-MG'], locations: [loc('Antananarivo', 'T')] },
  MU: {
    weight: 5,
    languages: ['en-MU', 'fr-MU'],
    locations: [loc('Port Louis', 'PL'), loc('Curepipe', 'PW')],
  },
  SC: { weight: 1, languages: ['en-SC', 'fr-SC'], locations: [loc('Victoria', '23')] },
  KM: { weight: 1, languages: ['fr-KM'], locations: [loc('Moroni', 'G')] },
  RE: { weight: 3, languages: ['fr-RE'], locations: [loc('Saint-Denis')] },
  YT: { weight: 1, languages: ['fr-YT'], locations: [loc('Mamoudzou')] },
  SH: { weight: 1, languages: ['en-GB'], locations: [loc('Jamestown', 'HL')] },
  // ── Americas ────────────────────────────────────────────────────────────
  GT: {
    weight: 10,
    languages: ['es-GT'],
    locations: [loc('Guatemala City', 'GU'), loc('Quetzaltenango', 'QZ')],
  },
  HN: {
    weight: 6,
    languages: ['es-HN'],
    locations: [loc('Tegucigalpa', 'FM'), loc('San Pedro Sula', 'CR')],
  },
  SV: {
    weight: 6,
    languages: ['es-SV'],
    locations: [loc('San Salvador', 'SS'), loc('Santa Ana', 'SA')],
  },
  NI: { weight: 5, languages: ['es-NI'], locations: [loc('Managua', 'MN'), loc('León', 'LE')] },
  CR: {
    weight: 10,
    languages: ['es-CR'],
    locations: [loc('San José', 'SJ'), loc('Alajuela', 'A'), loc('Heredia', 'H')],
  },
  PA: { weight: 8, languages: ['es-PA'], locations: [loc('Panama City', '8'), loc('Colón', '3')] },
  BZ: {
    weight: 2,
    languages: ['en-BZ'],
    locations: [loc('Belize City', 'BZ'), loc('Belmopan', 'CY')],
  },
  CU: {
    weight: 5,
    languages: ['es-CU'],
    locations: [loc('Havana', '03'), loc('Santiago de Cuba', '13')],
  },
  DO: {
    weight: 10,
    languages: ['es-DO'],
    locations: [loc('Santo Domingo', '01'), loc('Santiago', '25')],
  },
  HT: {
    weight: 4,
    languages: ['fr-HT', 'ht-HT'],
    locations: [loc('Port-au-Prince', 'OU'), loc('Cap-Haïtien', 'ND')],
  },
  JM: {
    weight: 6,
    languages: ['en-JM'],
    locations: [loc('Kingston', '01'), loc('Montego Bay', '08')],
  },
  PR: { weight: 8, languages: ['es-PR', 'en-US'], locations: [loc('San Juan'), loc('Ponce')] },
  TT: {
    weight: 4,
    languages: ['en-TT'],
    locations: [loc('Port of Spain', 'POS'), loc('San Fernando', 'SFO')],
  },
  BB: { weight: 2, languages: ['en-BB'], locations: [loc('Bridgetown', '08')] },
  BS: { weight: 2, languages: ['en-BS'], locations: [loc('Nassau', 'NP'), loc('Freeport', 'FP')] },
  BM: { weight: 2, languages: ['en-BM'], locations: [loc('Hamilton')] },
  KY: { weight: 2, languages: ['en-KY'], locations: [loc('George Town')] },
  VG: { weight: 1, languages: ['en-VG'], locations: [loc('Road Town')] },
  VI: { weight: 1, languages: ['en-VI'], locations: [loc('Charlotte Amalie')] },
  AG: { weight: 1, languages: ['en-AG'], locations: [loc('St. John’s', '04')] },
  DM: { weight: 1, languages: ['en-DM'], locations: [loc('Roseau', '04')] },
  GD: { weight: 1, languages: ['en-GD'], locations: [loc('St. George’s', '04')] },
  KN: { weight: 1, languages: ['en-KN'], locations: [loc('Basseterre', '03')] },
  LC: { weight: 1, languages: ['en-LC'], locations: [loc('Castries', '02')] },
  VC: { weight: 1, languages: ['en-VC'], locations: [loc('Kingstown', '04')] },
  AI: { weight: 1, languages: ['en-AI'], locations: [loc('The Valley')] },
  MS: { weight: 1, languages: ['en-MS'], locations: [loc('Brades')] },
  TC: { weight: 1, languages: ['en-TC'], locations: [loc('Cockburn Town')] },
  AW: { weight: 1, languages: ['nl-AW', 'en-US'], locations: [loc('Oranjestad')] },
  CW: { weight: 1, languages: ['nl-CW', 'en-US'], locations: [loc('Willemstad')] },
  SX: { weight: 1, languages: ['en-SX', 'nl-NL'], locations: [loc('Philipsburg')] },
  BQ: { weight: 1, languages: ['nl-BQ'], locations: [loc('Kralendijk', 'BO')] },
  BL: { weight: 1, languages: ['fr-BL'], locations: [loc('Gustavia')] },
  MF: { weight: 1, languages: ['fr-MF'], locations: [loc('Marigot')] },
  GP: { weight: 2, languages: ['fr-GP'], locations: [loc('Pointe-à-Pitre')] },
  MQ: { weight: 2, languages: ['fr-MQ'], locations: [loc('Fort-de-France')] },
  GF: { weight: 1, languages: ['fr-GF'], locations: [loc('Cayenne')] },
  PM: { weight: 1, languages: ['fr-PM'], locations: [loc('Saint-Pierre')] },
  BO: {
    weight: 8,
    languages: ['es-BO'],
    locations: [loc('La Paz', 'L'), loc('Santa Cruz de la Sierra', 'S'), loc('Cochabamba', 'C')],
  },
  PY: {
    weight: 6,
    languages: ['es-PY'],
    locations: [loc('Asunción', 'ASU'), loc('Ciudad del Este', '10')],
  },
  UY: {
    weight: 8,
    languages: ['es-UY'],
    locations: [loc('Montevideo', 'MO'), loc('Punta del Este', 'MA')],
  },
  GY: { weight: 2, languages: ['en-GY'], locations: [loc('Georgetown', 'DE')] },
  SR: { weight: 2, languages: ['nl-SR'], locations: [loc('Paramaribo', 'PM')] },
  FK: { weight: 1, languages: ['en-GB'], locations: [loc('Stanley')] },
  GL: { weight: 1, languages: ['da-GL', 'kl-GL'], locations: [loc('Nuuk', 'SM')] },
  // ── Asia-Pacific long tail ──────────────────────────────────────────────
  MN: { weight: 5, languages: ['mn-MN'], locations: [loc('Ulaanbaatar', '1')] },
  KP: { weight: 1, languages: ['ko-KP'], locations: [loc('Pyongyang', '01')] },
  MO: { weight: 4, languages: ['zh-MO', 'pt-MO'], locations: [loc('Macao')] },
  LA: { weight: 4, languages: ['lo-LA'], locations: [loc('Vientiane', 'VI')] },
  BN: { weight: 3, languages: ['ms-BN', 'en-US'], locations: [loc('Bandar Seri Begawan', 'BM')] },
  TL: { weight: 2, languages: ['pt-TL'], locations: [loc('Dili', 'DI')] },
  BT: { weight: 2, languages: ['dz-BT', 'en-US'], locations: [loc('Thimphu', '15')] },
  MV: { weight: 3, languages: ['dv-MV', 'en-US'], locations: [loc('Malé', 'MLE')] },
  AF: {
    weight: 6,
    languages: ['fa-AF', 'ps-AF'],
    locations: [loc('Kabul', 'KAB'), loc('Herat', 'HER')],
  },
  TJ: { weight: 4, languages: ['tg-TJ', 'ru-RU'], locations: [loc('Dushanbe', 'DU')] },
  KG: {
    weight: 5,
    languages: ['ky-KG', 'ru-RU'],
    locations: [loc('Bishkek', 'GB'), loc('Osh', 'GO')],
  },
  TM: { weight: 3, languages: ['tk-TM', 'ru-RU'], locations: [loc('Ashgabat', 'A')] },
  PG: {
    weight: 4,
    languages: ['en-PG'],
    locations: [loc('Port Moresby', 'NCD'), loc('Lae', 'MPL')],
  },
  FJ: { weight: 4, languages: ['en-FJ'], locations: [loc('Suva', 'C'), loc('Nadi', 'W')] },
  SB: { weight: 2, languages: ['en-SB'], locations: [loc('Honiara', 'GU')] },
  VU: { weight: 2, languages: ['en-VU', 'fr-VU'], locations: [loc('Port Vila', 'SEE')] },
  NC: { weight: 2, languages: ['fr-NC'], locations: [loc('Nouméa')] },
  PF: { weight: 2, languages: ['fr-PF'], locations: [loc('Papeete')] },
  WS: { weight: 2, languages: ['en-WS', 'sm-WS'], locations: [loc('Apia', 'TU')] },
  TO: { weight: 1, languages: ['en-TO', 'to-TO'], locations: [loc('Nuku’alofa', '04')] },
  KI: { weight: 1, languages: ['en-KI'], locations: [loc('Tarawa', 'G')] },
  FM: { weight: 1, languages: ['en-FM'], locations: [loc('Palikir', 'PNI')] },
  MH: { weight: 1, languages: ['en-MH'], locations: [loc('Majuro', 'MAJ')] },
  PW: { weight: 1, languages: ['en-PW'], locations: [loc('Ngerulmud', '212')] },
  NR: { weight: 1, languages: ['en-NR'], locations: [loc('Yaren', '14')] },
  TV: { weight: 1, languages: ['en-TV'], locations: [loc('Funafuti', 'FUN')] },
  GU: { weight: 2, languages: ['en-GU'], locations: [loc('Hagåtña')] },
  MP: { weight: 1, languages: ['en-MP'], locations: [loc('Saipan')] },
  AS: { weight: 1, languages: ['en-AS'], locations: [loc('Pago Pago')] },
  CK: { weight: 1, languages: ['en-CK'], locations: [loc('Avarua')] },
  NU: { weight: 1, languages: ['en-NU'], locations: [loc('Alofi')] },
  TK: { weight: 1, languages: ['en-TK'], locations: [loc('Nukunonu')] },
  WF: { weight: 1, languages: ['fr-WF'], locations: [loc('Mata-Utu')] },
  NF: { weight: 1, languages: ['en-AU'], locations: [loc('Kingston')] },
  CX: { weight: 1, languages: ['en-AU'], locations: [loc('Flying Fish Cove')] },
  CC: { weight: 1, languages: ['en-AU'], locations: [loc('West Island')] },
  PN: { weight: 1, languages: ['en-PN'], locations: [loc('Adamstown')] },
  // ── Europe long tail ────────────────────────────────────────────────────
  AD: { weight: 2, languages: ['ca-AD'], locations: [loc('Andorra la Vella', '07')] },
  MC: { weight: 2, languages: ['fr-MC'], locations: [loc('Monaco')] },
  SM: { weight: 1, languages: ['it-SM'], locations: [loc('San Marino', '07')] },
  VA: { weight: 1, languages: ['it-VA'], locations: [loc('Vatican City')] },
  LI: { weight: 2, languages: ['de-LI'], locations: [loc('Vaduz', '11')] },
  GI: { weight: 2, languages: ['en-GI'], locations: [loc('Gibraltar')] },
  JE: { weight: 2, languages: ['en-JE'], locations: [loc('Saint Helier')] },
  GG: { weight: 2, languages: ['en-GG'], locations: [loc('Saint Peter Port')] },
  IM: { weight: 2, languages: ['en-IM'], locations: [loc('Douglas')] },
  FO: { weight: 1, languages: ['fo-FO', 'da-DK'], locations: [loc('Tórshavn')] },
  AX: { weight: 1, languages: ['sv-AX'], locations: [loc('Mariehamn')] },
  SJ: { weight: 1, languages: ['nb-SJ'], locations: [loc('Longyearbyen')] },
  EH: { weight: 1, languages: ['ar-EH', 'es-ES'], locations: [loc('Laayoune')] },
  // ── Uninhabited or near-uninhabited territories (rare) ──────────────────
  AQ: { weight: 1, languages: ['en-US'], locations: [loc('McMurdo Station')] },
  BV: { weight: 1, languages: ['nb-NO'], locations: [loc('')] },
  GS: { weight: 1, languages: ['en-GB'], locations: [loc('King Edward Point')] },
  HM: { weight: 1, languages: ['en-AU'], locations: [loc('')] },
  IO: { weight: 1, languages: ['en-GB'], locations: [loc('Diego Garcia')] },
  TF: { weight: 1, languages: ['fr-FR'], locations: [loc('Port-aux-Français')] },
  UM: { weight: 1, languages: ['en-US'], locations: [loc('')] },
};

const countryWeights: WeightedOption<string>[] = Object.entries(countries).map(
  ([value, { weight }]) => ({ value, weight }),
);

export const seededCountryCodes = Object.keys(countries);

export function getRandomGeo(): GeoLocation {
  const country = weightedRandom(countryWeights);
  const { region, city } = pickRandom(countries[country].locations);

  return {
    country,
    // Stored the way the tracker does it: full ISO 3166-2 code, e.g. "US-CA".
    region: region ? `${country}-${region}` : '',
    city,
  };
}

const fallbackLanguages: WeightedOption<string>[] = [
  { value: 'en-US', weight: 0.6 },
  { value: 'en-GB', weight: 0.2 },
  { value: 'es-ES', weight: 0.05 },
  { value: 'fr-FR', weight: 0.05 },
  { value: 'zh-CN', weight: 0.05 },
  { value: 'ar-SA', weight: 0.05 },
];

export function getRandomLanguage(country?: string): string {
  const languages = country ? countries[country]?.languages : undefined;

  if (languages?.length) {
    // Most visitors use a local language; a minority browse in English.
    return Math.random() < 0.9 ? pickRandom(languages) : 'en-US';
  }

  return weightedRandom(fallbackLanguages);
}
